apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # these lables are replicaset lables
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these labels shoul match with pod lables
      tier: frontend
      app: nginx
      environment: dev
  template: # this one is nothing but pod definition
    metadata:
      labels:
        tier: frontend
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx