apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these lables are replicaset lables
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these labels shoul match with pod lables
      app: nginx
      project: roboshop
      component: frontend
  template: # this one is nothing but pod definition
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80