apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    env: prod
    app: nginx
  annotations:
    com.project.author: sureshvadde
    com.project.name: roboshop
spec:
  containers:
  - name: nginx-labels
    image: nginx:1.14.2
    imagePullPolicy: Always
    env:
      - name: course
        value: "DevOps"
      - name: duration
        value: "120hrs"
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
    
