apiVersion: v1
kind: Pod
metadata:
  name: configpod
spec:
  containers:
  - name: configpod
    image: nginx
    env:
    - name: course
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: duration    

