apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: YWJjMTIzCg==
  username: c3VyZXNoCg==

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    envFrom:
    - secretRef:
        name: mysecret


